n = int(input('Digite um número para ver sua tabuada: '))
a = n * 1
b = n * 2
c = n * 3
d = n * 4
e = n * 5
f = n * 6
g = n * 7
h = n * 8
i = n * 9
j = n * 10

print(f'{n} * 1 = {a}')
print(f'{n} * 2 = {b}')
print(f'{n} * 3 = {c}')
print(f'{n} * 4 = {d}')
print(f'{n} * 5 = {e}')
print(f'{n} * 6 = {f}')
print(f'{n} * 7 = {g}')
print(f'{n} * 8 = {h}')
print(f'{n} * 9 = {i}')
print(f'{n} * 10 = {j}')